blank_issues_enabled: false
contact_links:
  - name: Repositório do Projeto - G3 Streaming de Vídeo
    url: https://github.com/UnBArqDsw2026-2-Turma02/2026.2_T02_G3_ProjetoStreamingVideo_Entrega_01
    about: Repositório do Grupo 3 (Streaming de Vídeo), Turma 02, semestre 2026.2.